development:
  adapter: postgresql
  encoding: unicode
  database: tour_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: tour_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tour_production
  host: localhost

cucumber:
  <<: *test